#!/bin/bash
# vim: set ft=sh

set -ex

cd nfsv3driver

export GOROOT=/usr/local/go
export PATH=$GOROOT/bin:$PATH

if ! ginkgo version &> /dev/null
then
  go install github.com/onsi/ginkgo/v2/ginkgo@latest
fi

./scripts/run-unit-tests -race
