#!/bin/bash

set -ex

pushd $(dirname $0)/..
  ginkgo -keep-going -p -race -trace -randomize-all -show-node-events "$@"
  pushd cmd/nfsv3driver
    ginkgo -keep-going -race -trace -randomize-all -show-node-events "$@"
  popd
popd
