#!/bin/bash

set -ex

export GO111MODULE=on

pushd $(dirname $0)/..
  ginkgo -keepGoing -p -race -trace -randomizeAllSpecs -progress "$@"
  pushd cmd/nfsv3driver
    ginkgo -keepGoing -race -trace -randomizeAllSpecs -progress "$@"
  popd
popd
