// Code generated by counterfeiter. DO NOT EDIT.
package nfsdriverfakes

import (
	"context"
	"sync"
	"time"

	"code.cloudfoundry.org/dockerdriver"
	"code.cloudfoundry.org/nfsv3driver"
)

type FakeBackgroundInvoker struct {
	InvokeStub        func(dockerdriver.Env, string, []string, string, time.Duration) (error, context.CancelFunc)
	invokeMutex       sync.RWMutex
	invokeArgsForCall []struct {
		arg1 dockerdriver.Env
		arg2 string
		arg3 []string
		arg4 string
		arg5 time.Duration
	}
	invokeReturns struct {
		result1 error
		result2 context.CancelFunc
	}
	invokeReturnsOnCall map[int]struct {
		result1 error
		result2 context.CancelFunc
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBackgroundInvoker) Invoke(arg1 dockerdriver.Env, arg2 string, arg3 []string, arg4 string, arg5 time.Duration) (error, context.CancelFunc) {
	var arg3Copy []string
	if arg3 != nil {
		arg3Copy = make([]string, len(arg3))
		copy(arg3Copy, arg3)
	}
	fake.invokeMutex.Lock()
	ret, specificReturn := fake.invokeReturnsOnCall[len(fake.invokeArgsForCall)]
	fake.invokeArgsForCall = append(fake.invokeArgsForCall, struct {
		arg1 dockerdriver.Env
		arg2 string
		arg3 []string
		arg4 string
		arg5 time.Duration
	}{arg1, arg2, arg3Copy, arg4, arg5})
	fake.recordInvocation("Invoke", []interface{}{arg1, arg2, arg3Copy, arg4, arg5})
	fake.invokeMutex.Unlock()
	if fake.InvokeStub != nil {
		return fake.InvokeStub(arg1, arg2, arg3, arg4, arg5)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.invokeReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBackgroundInvoker) InvokeCallCount() int {
	fake.invokeMutex.RLock()
	defer fake.invokeMutex.RUnlock()
	return len(fake.invokeArgsForCall)
}

func (fake *FakeBackgroundInvoker) InvokeCalls(stub func(dockerdriver.Env, string, []string, string, time.Duration) (error, context.CancelFunc)) {
	fake.invokeMutex.Lock()
	defer fake.invokeMutex.Unlock()
	fake.InvokeStub = stub
}

func (fake *FakeBackgroundInvoker) InvokeArgsForCall(i int) (dockerdriver.Env, string, []string, string, time.Duration) {
	fake.invokeMutex.RLock()
	defer fake.invokeMutex.RUnlock()
	argsForCall := fake.invokeArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4, argsForCall.arg5
}

func (fake *FakeBackgroundInvoker) InvokeReturns(result1 error, result2 context.CancelFunc) {
	fake.invokeMutex.Lock()
	defer fake.invokeMutex.Unlock()
	fake.InvokeStub = nil
	fake.invokeReturns = struct {
		result1 error
		result2 context.CancelFunc
	}{result1, result2}
}

func (fake *FakeBackgroundInvoker) InvokeReturnsOnCall(i int, result1 error, result2 context.CancelFunc) {
	fake.invokeMutex.Lock()
	defer fake.invokeMutex.Unlock()
	fake.InvokeStub = nil
	if fake.invokeReturnsOnCall == nil {
		fake.invokeReturnsOnCall = make(map[int]struct {
			result1 error
			result2 context.CancelFunc
		})
	}
	fake.invokeReturnsOnCall[i] = struct {
		result1 error
		result2 context.CancelFunc
	}{result1, result2}
}

func (fake *FakeBackgroundInvoker) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.invokeMutex.RLock()
	defer fake.invokeMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBackgroundInvoker) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ nfsv3driver.BackgroundInvoker = new(FakeBackgroundInvoker)
